_ZadatkoMoj/_Zadatko/Models/Zadaci.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _Zadatko.Models
{
    public class Zadaci
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Naziv { get; set; }

        [Required]
        [Range(1,10)]
        public int Tezina { get; set; }

        [Required]
        [Range(1, 10)]
        public int Vaznost { get; set; }

        [Required]
        [StringLength(100)]
        public string KratkiOpis { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime RokObavljanja { get; set; }

        [Required]
        [Range(1, 100)]
        public int PostotnaRjesenostZadatka { get; set; }

        [Required]
        public string KorisnikID { get; set; }
    }
}

_ZadatkoMoj/_Zadatko/Controllers/ZadaciController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _Zadatko.Models;
using Microsoft.AspNet.Identity;


namespace _Zadatko.Controllers
{
    public class ZadaciController : Controller
    {
        private ZadaciContext db = new ZadaciContext();

        // GET: Zadaci
        [Authorize]
        public ActionResult Index(string searchBy, string search, int? page)
        {
           

            /*
             var zadaci = from s in db.Zadacis
                           select s;
                */
        

            if (searchBy == null)
            {
                return View(db.Zadacis.ToList());
            }
            else
            {
               
                

                switch (searchBy)
                {
                    case "Svi":
                        return View(db.Zadacis);

                    case "Utijeku":
                        //zadaci u tijeku su oni zadaci ciji je progress manji od 100%, a rok obavljavanja je u buducnosti negdje
                        return View(db.Zadacis.Where(s => s.PostotnaRjesenostZadatka < 100).Where(s => s.RokObavljanja > DateTime.Now));

                    case "Obavljene":
                        //obavljeni zadaci su oni ciji je progress 100%
                        return View(db.Zadacis.Where(s => s.PostotnaRjesenostZadatka == 100));

                    case "Istekli":
                        //istekli zadaci su oni ciji je progress manji od 100%, a rok obavljanja je negdje u proslosti
                        return View(db.Zadacis.Where(s => s.PostotnaRjesenostZadatka < 100).Where(s => s.RokObavljanja < DateTime.Now));

                    case "Kljucne":
                        //ako se odabere pretraga po kljucnim rijecima,onda gledam sadrzi li tekst objave tu rijec
                        //ako ne , onda provjeravam sadrzi li naslov,ako ne ,onda se vraca prazan model
                        if (db.Zadacis.Where(x => x.Naziv.Contains(search)).ToList().Count() >= 1)
                        {
                            return View(db.Zadacis.Where(x => x.Naziv.Contains(search) || search == null).ToList());
                        }
                        else if (db.Zadacis.Where(x => x.KratkiOpis.Contains(search)).ToList().Count() >= 1)
                        {
                            return View(db.Zadacis.Where(x => x.KratkiOpis.Contains(search) || search == null));
                        }
                        else
                        {
                            List<Zadaci> prazniModel = new List<Zadaci>();
                            return View(prazniModel);
                        }
                        

                    default:
                        //po defuatlu inace vracam sve zadatke
                        return View(db.Zadacis.ToList());

                }
            }


        }

        // GET: Zadaci/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zadaci zadaci = db.Zadacis.Find(id);
            if (zadaci == null)
            {
                return HttpNotFound();
            }
            return View(zadaci);
        }

        // GET: Zadaci/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Zadaci/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv,Tezina,Vaznost,KratkiOpis,RokObavljanja,PostotnaRjesenostZadatka,KorisnikID")] Zadaci zadaci)
        {
            
            zadaci.KorisnikID= User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Zadacis.Add(zadaci);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(zadaci);

          
        }


        // GET: Zadaci/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zadaci zadaci = db.Zadacis.Find(id);
            if (zadaci == null)
            {
                return HttpNotFound();
            }
            return View(zadaci);
        }

        // POST: Zadaci/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv,Tezina,Vaznost,KratkiOpis,RokObavljanja,PostotnaRjesenostZadatka,KorisnikID")] Zadaci zadaci)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zadaci).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(zadaci);
        }

        // GET: Zadaci/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zadaci zadaci = db.Zadacis.Find(id);
            if (zadaci == null)
            {
                return HttpNotFound();
            }
            return View(zadaci);
        }

        // POST: Zadaci/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zadaci zadaci = db.Zadacis.Find(id);
            db.Zadacis.Remove(zadaci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

_ZadatkoMoj/_Zadatko/Views/Zadaci/Create.cshtml
@model _Zadatko.Models.Zadaci
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Kreiranje zadatka";
}

<h2>Kreiranje novog zadatka </h2>





@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ispunite formu osnovnim informacijama o zadatku kako biste ga dodali.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, "Naziv:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tezina,"Težina (1-10):", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tezina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tezina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vaznost, "Važnost (1-10):", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vaznost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vaznost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KratkiOpis,"Kratki opis:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KratkiOpis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KratkiOpis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RokObavljanja,"Rok obavljanja:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RokObavljanja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RokObavljanja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostotnaRjesenostZadatka,"Do sada rješeno (u %):", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostotnaRjesenostZadatka, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostotnaRjesenostZadatka, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KorisnikID,"Vaš potpis:", htmlAttributes: new { @class = "control-label col-md-2", @Value="6545"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.KorisnikID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KorisnikID, "", new { @class = "text-danger" })
            </div>
        </div>

     
   

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kreiraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na popis", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

_ZadatkoMoj/_Zadatko/Views/Zadaci/Delete.cshtml
@model _Zadatko.Models.Zadaci

@{
    ViewBag.Title = "Brisanje zadatka";
}

<h2>Izbriši</h2>

<h3>Jeste li sigurni da želite izbrisati ovaj zadatak?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            Težina (1-10):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tezina)
        </dd>

        <dt>
            Važnost (1-10):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vaznost)
        </dd>

        <dt>
            Kratki opis:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KratkiOpis)
        </dd>

        <dt>
            Rok obavljanja:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RokObavljanja)
        </dd>

        <dt>
            Do sada rješeno: (u %)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostotnaRjesenostZadatka)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-default" /> |
            @Html.ActionLink("Povratak na popis", "Index")
        </div>
    }
</div>

_ZadatkoMoj/_Zadatko/Views/Zadaci/Details.cshtml
@model _Zadatko.Models.Zadaci

@{
    ViewBag.Title = "Detalji";
}

<h2>Detalji</h2>

<div>
    <h4>Pregled informacija vezanih za konkretni zadatak.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            Težina (1-10):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tezina)
        </dd>

        <dt>
            Važnost (1-10):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vaznost)
        </dd>

        <dt>
            Kratki opis:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KratkiOpis)
        </dd>

        <dt>
            Rok obavljanja:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RokObavljanja)
        </dd>

        <dt>
            Do sada rješeno: (u %)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostotnaRjesenostZadatka)
        </dd>

         <!-- ne zelim prikazivat id korisniku  ,drzim jedino u svrhe debugiranja aplikacije
        <dt>
            @Html.DisplayNameFor(model => model.KorisnikID)
        </dt>

       
        <dd>
            @Html.DisplayFor(model => model.KorisnikID)
        </dd>
            -->

    </dl>
</div>
<p>
    @Html.ActionLink("Uredi", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Povratak na popis", "Index")
</p>

_ZadatkoMoj/_Zadatko/Views/Zadaci/Edit.cshtml
@model _Zadatko.Models.Zadaci

@{
    ViewBag.Title = "Uređivanje zadatka";
}

<h2>Uredi</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ovdje možete izmjeniti informacije o zadatku.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tezina,"Težina (1-10)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tezina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tezina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vaznost, "Važnost (1-10)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vaznost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vaznost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KratkiOpis, "Kratki opis", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KratkiOpis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KratkiOpis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RokObavljanja, "Rok obavljanja", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RokObavljanja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RokObavljanja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostotnaRjesenostZadatka, "Do sada rješeno (u %)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostotnaRjesenostZadatka, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostotnaRjesenostZadatka, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- ne zelim id prikazat korisniku !-->
        <div class="form-group">
          
            <div class="col-md-10">
                @Html.HiddenFor(model => model.KorisnikID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KorisnikID, "", new { @class = "text-danger" })
            </div>
        </div>
           

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na popis", "Index")
</div>


@ViewBag.testic

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

_ZadatkoMoj/_Zadatko/Views/Zadaci/Index.cshtml
@model IEnumerable<_Zadatko.Models.Zadaci>
@using Microsoft.AspNet.Identity;
@using _Zadatko.Extensions;
@using System.Text.RegularExpressions;

@{
    ViewBag.Title = "Moji zadaci";
}
<!--ukoliko nisu sva imena korisnika u bazi napisana prvim slovim velikim:-->
<h2>Bok @Regex.Replace(User.Identity.GetIme(), @"^\w", m => m.Value.ToUpper()) ! Ovo su tvoji zadaci: @ViewBag.testic</h2>
<hr/>


<div class="row">
    <div class="col-lg-5">
        @Html.ActionLink("Dodaj novi zadatak", "Create", null, new { @class = "btn btn-default" })
    </div>
    <div class="col-lg-7">

       <!-- filter pretraga s 4 razlciita parametra: i mogucnoscu pretrage po nazivu-->
            @using (@Html.BeginForm("Index", "Zadaci", FormMethod.Get))
            {
                <b>Način prikaza:</b>
                @Html.RadioButton("searchBy", "Svi", true) <text>Svi</text>
                @Html.RadioButton("searchBy", "Utijeku") <text>U tijeku</text>
                @Html.RadioButton("searchBy", "Obavljene") <text>Obavljeni</text>
                @Html.RadioButton("searchBy", "Istekli") <text>Istekli</text>
                @Html.RadioButton("searchBy", "Kljucne") <text>Ključne riječi</text>
                <br />
               
               @Html.TextBox("search") <input type="submit" value="Prikaži" class="btn btn-default tanki" />
               
               
            }
       

    </div>
    </div>
<hr/>


 <div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

            @foreach (var item in Model)
            {
                //dakle,prikazujem zadatke samo onog korisnika koji je trenutno ulogiran. ("marka ne zanimaju zadaci koje ima luka"):
                if (item.KorisnikID == User.Identity.GetUserId())
                {

                        <div class="post-preview">
                            <a>
                                <h2 class="post-title">
                                    @{bool Zakasnio = false;}

                                   @{  
                                       if (item.PostotnaRjesenostZadatka == 100)
                                       {
                                           //ako je progress na 100%,znaci da je zadatak obavljen u cijelosti
                                           //pa kao indikator postavljam ikonu kvačice
                                        <span class="fa-stack fa-md" title="obavljeno">
                                            <i class="fa fa-circle fa-stack-2x"></i>
                                            <i class="fa fa-check fa-stack-1x fa-inverse"></i>
                                        </span>

                                       }
                                       else if (item.RokObavljanja < DateTime.Now)
                                       {
                                           //ako je progres manji od 100%, a rok obavljanja zadatka je vec prosao ,onda to znaci
                                           //da korisnik nije ispostivao rok koji je sam sebi zadao,pa prema tome stavljam simbol
                                           //"x" kraj objave zadatka (posta)
                                           Zakasnio = true;
                                            <span class="fa-stack fa-md" title="obavljeno">
                                                <i class="fa fa-circle fa-stack-2x"></i>
                                                <i class="fa fa-times fa-stack-1x fa-inverse"></i>
                                            </span>
                                       }
                                       else
                                        {
                                            //inace,zadatak se jos uvijek obavlja pa stavljam ikonu olovke i kartončića
                                                <span class="fa-stack fa-md" title="u tijeku">
                                                    <i class="fa fa-circle fa-stack-2x"></i>
                                                    <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                                </span>
                                        }
                                      }
                                    @Html.DisplayFor(modelItem => item.Naziv)
                                </h2>
                                <h3 class="post-subtitle">
                                    @Html.DisplayFor(modelItem => item.KratkiOpis)
                                </h3>
                            </a>
                            
                            @Html.DisplayFor(modelItem => item.Vaznost)
                            <span class="fa-stack fa-lg" title="vaznost">
                                <i class="fa fa-circle fa-stack-1x"></i>
                                <i class="fa fa-exclamation fa-stack-1x fa-inverse"></i>
                            </span>
                            @Html.DisplayFor(modelItem => item.Tezina)
                            <span class="fa-stack fa-lg" title="tezina">
                                <i class="fa fa-circle fa-stack-1x"></i>
                                <i class="fa fa-gears fa-stack-1x fa-inverse"></i>
                            </span>

                            <!--napravljeni progres u postoticma:-->
                          
                            <div class="progress">
                                @{

                                    if (item.PostotnaRjesenostZadatka == 100 || Zakasnio == true)
                                    {
                                        <div class="progress-bar" role="progressbar"
                                             aria-valuenow=@item.PostotnaRjesenostZadatka.ToString() aria-valuemin="0" aria-valuemax="100" style="width:@item.PostotnaRjesenostZadatka%">
                                            @Html.DisplayFor(modelItem => item.PostotnaRjesenostZadatka)%
                                        </div>
                                    }
                                    else
                                    {
                                         <div class="progress-bar progress-bar-striped active" role="progressbar"
                                     aria-valuenow=@item.PostotnaRjesenostZadatka.ToString() aria-valuemin="0" aria-valuemax="100" style="width:@item.PostotnaRjesenostZadatka%">
                                    @Html.DisplayFor(modelItem => item.PostotnaRjesenostZadatka)%
                                </div>
                                    }
                                 }
                               
                                    
                            </div>  

                            <!--ovaj id sam ispisivao samo u svrhu debugiranja ,al inace to korisniku ne treba bit vidljivo
                            <h3 class="post-subtitle">id | @Html.DisplayFor(modelItem => item.KorisnikID) </h3>
                             -->

                            @{
                                if (Zakasnio == true)
                                {
                                    <p class="post-meta" id="zakasnio"> Ovaj zadatak ste trebali napraviti <b>najkasnije</b> do: @Html.DisplayFor(modelItem => item.RokObavljanja) </p>
                                }
                                else
                                {
                                    if (item.PostotnaRjesenostZadatka == 100)
                                    {
                                        <p class="post-meta" id="uspio"> Zadatak je obavljen. (Krajnji rok je bio: @Html.DisplayFor(modelItem => item.RokObavljanja)) </p>
                                    }
                                    else
                                    {
                                        <p class="post-meta"> Napraviti najkasnije do: @Html.DisplayFor(modelItem => item.RokObavljanja) </p>
                                    }

                                }
                            }
                           


                            @Html.ActionLink("Uredi", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Detalji", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Izbriši", "Delete", new { id = item.Id })
                              
                        </div>
                        <hr>
                }
            }

         

        </div>
    </div>
</div>